kind: ZarfPackageConfig
metadata:
  name: farmer-pickles
  url: https://welovebob.com/characters/farmer_pickles.htm
  image: https://welovebob.com/Images/characters/farmer_pickles.jpg
  description: "A zarf package to deploy things"

components:
  - name: deploy
    required: true
    actions:
      onCreate:
        before:
          - description: Deploy a k3d cluster with istio
            cmd: |
              ../build/uds deploy oci://ghcr.io/zachariahmiller/k3d-common-istio:0.2.0-amd64 --confirm
          - description: Deploy the package
            cmd: |
              ./zarf package deploy ../build/zarf-package-postgres-operator-* --confirm
