# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/zarf/main/zarf.schema.json
kind: ZarfPackageConfig
metadata:
  name: postgres-test
  description: "A test deployment of zalando postgres"

components:
  - name: postgres
    required: true
    manifests:
      - name: postgres
        files:
          - postgres-svc.yaml
          - postgres-minimal.yaml
    actions:
      onDeploy:
        after:
          - wait:
              cluster:
                kind: Postgresql
                name: pg-cluster
                namespace: acid
                condition: "'{.status.PostgresClusterStatus}'=Running"
